djangotest/djangotest/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.views.decorators.cache import cache_control
# from django.contrib.staticfiles.views import serve
# from django.conf.urls.static import static
# from . import settings

app_name = 'polls'

urlpatterns = [
    path(f'{app_name}/', include(f'{app_name}.urls')),
    path('admin/', admin.site.urls),
]

# urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

djangotest/polls/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf import settings
# from django.conf.urls.static import static

from . import views

# Register app namespace : IMPORTANT !
app_name = "polls"

urlpatterns = [
    # ex: /polls/
    path(
        route='',                           # string containing a URL pattern
        view=views.IndexView.as_view(),     # call the specified view function upon finding a matching pattern
        name='index'                        # set a name for URL
    ),
    # ex: /polls/5/
    path(route='<int:pk>/', view=views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path(route='<int:pk>/results/', view=views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path(route='<int:pk>/vote/', view=views.vote, name='vote'),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangotest/testapp/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.conf import settings
# from django.conf.urls.static import static

from . import views

# Register app namespace : IMPORTANT !
app_name = "testapp"

urlpatterns = [
    # ex: /testapp/
    path(
        route='',                           # string containing a URL pattern
        view=views.IndexView.as_view(),     # call the specified view function upon finding a matching pattern
        name='index'                        # set a name for URL
    ),
    # ex: /testapp/5/
    path(route='<int:pk>/', view=views.DetailView.as_view(), name='detail'),
    # ex: /testapp/5/results/
    path(route='<int:pk>/results/', view=views.ResultsView.as_view(), name='results'),
    # ex: /testapp/5/vote/
    path(route='<int:pk>/vote/', view=views.vote, name='vote'),
]

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangotest/testapp/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

app_name = "testapp"

# ListView : display a list of objects
class IndexView(generic.ListView):
    template_name = f'{app_name}/index.html'
    context_object_name = 'latest_question_list'            # to override the automatically generated context variable

    def get_queryset(self):
        """
        Return the last five published questions.
        Excludes questions set to be published in the future, nor those with 1 or 0 choices.
        """

        # Filter on date
        qset = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

        # Filter on number of choices : uses a model method, thus has to be done through list comprehension
        qset = qset.filter(id__in=[question.id for question in qset if question.has_enough_choices()])

        # Return 5 most recent questions
        return qset[:5]


# DetailView : display a detail page for a particular type of object
# Expects the primary key value captured from the URL to be called "pk"
class DetailView(generic.DetailView):
    model = Question
    template_name = f'{app_name}/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet + those with 1 or 0 choices
        """
        qset = Question.objects.filter(pub_date__lte=timezone.now())
        qset = qset.filter(id__in=[question.id for question in qset if question.has_enough_choices()])
        return qset


class ResultsView(generic.DetailView):
    model = Question
    template_name = f'{app_name}/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet + those with 1 or 0 choices
        """
        qset = Question.objects.filter(pub_date__lte=timezone.now())
        qset = qset.filter(id__in=[question.id for question in qset if question.has_enough_choices()])
        return qset


def vote(request: HttpRequest, pk: int):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])        # access submitted data
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(
            request=request,
            template_name=f'{app_name}/detail.html',
            context={
                'question': question,
                'error_message': "You didn't make a choice.",
            }
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()

        # GOOD WEB DEV PRACTICE
        # Always return an HttpResponseRedirect after successfully dealing with POST data.
        # This prevents data from being posted twice if a user hits the Back button.
        return HttpResponseRedirect(reverse(viewname=f'{app_name}:results', args=(question.id,)))

djangotest/testapp/templates/testapp/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>

<body>
    <!-- Will alter data server-side, thus POST -->
    <form action="{% url 'testapp:vote' question.id %}" method="post">
        <!-- Protection against Cross Site Request Forgeries for forms targeted at internal URLs -->
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>

</html>

djangotest/testapp/templates/testapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'testapp/style.css' %}">
    <title>Index</title>
</head>

<body>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'testapp:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>

</html>

djangotest/testapp/templates/testapp/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} >> {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'testapp:detail' question.id %}">Vote again?</a>
</body>

</html>